# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/counter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/counter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/counter.proto\x12\x07\x63ounter\" \n\x10\x43haracterRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\"\n\x11\x43haracterResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32W\n\x07\x43ounter\x12L\n\x0f\x43ountCharacters\x12\x19.counter.CharacterRequest\x1a\x1a.counter.CharacterResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.counter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHARACTERREQUEST']._serialized_start=33
  _globals['_CHARACTERREQUEST']._serialized_end=65
  _globals['_CHARACTERRESPONSE']._serialized_start=67
  _globals['_CHARACTERRESPONSE']._serialized_end=101
  _globals['_COUNTER']._serialized_start=103
  _globals['_COUNTER']._serialized_end=190
# @@protoc_insertion_point(module_scope)
